sudo: required
branches:
  only:
    - CI
os: linux
dist: trusty
language: python
python:
- '2.7'
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
before_install:
- openssl aes-256-cbc -K $encrypted_5aee36c2e1b9_key -iv $encrypted_5aee36c2e1b9_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- if [ ! -d ${HOME}/google-cloud-sdk ]; then curl https://sdk.cloud.google.com | bash;
  fi
- tar -xzf credentials.tar.gz
- mkdir -p lib
jobs:
  include:
  - stage: deploy
    deploy:
      provider: gae
      skip_cleanup: true
      keyfile: client-secret.json
      project: cv-steelconnect
      version: 1
      on:
        all_branches: true
    script: skip
  - stage: botium_test
    script:
    - "./login.sh"
    - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
    - nvm install 10.8.0
    - nvm use 10.8.0
    - npm list -g botium-cli --depth=0 || npm install -g botium-cli@0.0.22
    - botium-cli run
stages:
- deploy
- botium_test
