sudo: false
os: linux
dist: trusty
language: python
python:
- '2.7'
# Cache our Gcloud SDK between commands
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
  #- $(npm config get prefix)/lib/botium-cli
before_install:
# [START auth]
- openssl aes-256-cbc -K $encrypted_5aee36c2e1b9_key -iv $encrypted_5aee36c2e1b9_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- if [ ! -d ${HOME}/google-cloud-sdk ]; then
    curl https://sdk.cloud.google.com | bash;
  fi
- if [ ! -d $/home/travis/.nvm/versions/node/v8.9.1/lib/botium-cli]; then
    npm install -g botium-cli;
  fi
- tar -xzf credentials.tar.gz
- mkdir -p lib

jobs:
  include:
    - stage: deploy
      script: skip    
      deploy:
        provider: gae
        skip_cleanup: true
        keyfile: client-secret.json
        project: cv-steelconnect
        version: 1
        on:
          all_branches: true
    - stage: botium_test
      script:
        - botium-cli run

stages:
  #- deploy
  - botium_test
