sudo: false
os: linux
dist: trusty
language: python
python:
- '2.7'
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
  - "$(npm config get prefix)/lib/botium-cli"
before_install:
- openssl aes-256-cbc -K $encrypted_5aee36c2e1b9_key -iv $encrypted_5aee36c2e1b9_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- if [ ! -d ${HOME}/google-cloud-sdk ]; then curl https://sdk.cloud.google.com | bash;
  fi
- 
- tar -xzf credentials.tar.gz
- mkdir -p lib
jobs:
  include:
  - stage: deploy
    deploy:
      provider: gae
      skip_cleanup: true
      keyfile: client-secret.json
      project: cv-steelconnect
      version: 1
      on:
        all_branches: true
    script:
    - curl --netrc-file login.netrc https://cv-steelconnect.appspot.com/authenticate
  - stage: botium_test
    script:
    - botium-cli run
stages:
- deploy
- 
