# Don't build a vanilla environment for every build
sudo: false
os: linux
dist: trusty
language: python
python:
- '3.6'
before_install:
- openssl aes-256-cbc -K $encrypted_86a5c3fbef7c_key -iv $encrypted_86a5c3fbef7c_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
- tar -xzf credentials.tar.gz
- mkdir -p lib

script:
  - echo "No script to run"
  - ls

deploy:
  provider: cv-steelconnect
  skip_cleanup: true
  keyfile: client-secret.json
  project: cv-steelconnect
  version: 1
  on:
    all_branches: true

